import streamlit as st
from database import get_connection, delete_user
from database import get_user_profile
from database import get_all_users, get_plan_history
from datetime import datetime, timedelta
from database import get_user_progress,delete_plan
import pandas as pd

ADMIN_USER = st.secrets["ADMIN_USER"]
ADMIN_PASS = st.secrets["ADMIN_PASS"]

st.set_page_config("Admin", "📊")

if "admin" not in st.session_state:
    st.session_state.admin = False

if not st.session_state.admin:
    st.title("🔐 Admin Login")

    u = st.text_input("Admin Username")
    p = st.text_input("Admin Password", type="password")

    if st.button("Login"):
        if u == ADMIN_USER and p == ADMIN_PASS:
            st.session_state.admin = True
            st.session_state.admin_username = u
            st.success("✅ Admin login successful")
            st.rerun()
        else:
            st.error("❌ Invalid admin username or password")

    st.stop()

if st.sidebar.button("Logout"):
    st.session_state.admin = False
    st.session_state.pop("admin_id", None)
    st.session_state.pop("admin_username", None)
    st.rerun()

st.title("Admin Dashboard")
conn = get_connection()
cursor = conn.cursor()
cursor.execute("SELECT id, username FROM users")
users = cursor.fetchall()
cursor.close()
conn.close()
for uid, u in users:
    c1, c2, c3 = st.columns([4,2,2])
    c1.write(u)
    if c2.checkbox("Confirm", key=uid) and c3.button("Delete", key=f"d{uid}"):
        delete_user(uid)
        st.rerun()

selected_profile_user = None

st.subheader("👤 User Profile Details")

users = get_all_users()

if not users:
    st.info("No users found.")
else:
    user_map = {u[1]: u[0] for u in users}

    selected_profile_user = st.selectbox(
        "Select a user to view profile",
        list(user_map.keys()),
        key="profile_viewer"
    )

    profile_uid = user_map[selected_profile_user]

    profile = get_user_profile(profile_uid)

    if not profile:
        st.warning("No profile data available for this user.")
    else:
        age, height, weight, state, city, goal, diet, workout_place, budget = profile

        c1, c2, c3 = st.columns(3)

        c1.metric("Age", age)
        c1.metric("Height (cm)", height)
        c1.metric("Weight (kg)", weight)

        c2.metric("State", state)
        c2.metric("City", city)
        c2.metric("Goal", goal)

        c3.metric("Diet", diet)
        c3.metric("Workout Place", workout_place)
        c3.metric("Budget (₹)", budget)


st.subheader("📈 User Progress Trends")

# ---- ISSUE 5 FIX: guard before showing progress ----
if not selected_profile_user:
    st.info("👆 Please select a user to view progress and history.")
    st.stop()

progress = get_user_progress(profile_uid)
dates = []
weights = []

# ✅ ADD WEEK 1 BASELINE FROM PROFILE
profile = get_user_profile(profile_uid)
if profile:
    _, _, weight, *_ = profile
    if weight:
        dates.append("Current")
        weights.append(weight)

# ✅ ADD WEEK 2+ PROGRESS
for week, weight,_, ts in progress:
    dates.append(f"Week {week}")
    weights.append(weight)


df_weight = pd.DataFrame({
    "Date": dates,
    "Weight (kg)": weights
})

if len(weights) < 2:
    st.info("Not enough data to show progress trend.")
else:
    st.line_chart(df_weight, x="Date", y="Weight (kg)")


st.subheader("📜 User Plan History")

history = get_plan_history(profile_uid)

if not history:
    st.info("No plans generated by this user.")
else:
    for plan_id, week, plan, ts in history:
        ist_time = ts + timedelta(hours=5, minutes=30)

        with st.expander(f"🗓️ Week {week} — {ist_time.strftime('%d %b %Y, %I:%M %p')}"):
            st.markdown(plan)

            col1, col2 = st.columns([4,1])

            with col2:
                if st.checkbox("Confirm delete", key=f"confirm_{plan_id}"):
                    if st.button("🗑️ Delete Plan", key=f"delete_{plan_id}"):
                        delete_plan(plan_id)
                        st.success(f"✅ Week {week} plan deleted")

                        st.rerun()
